### ISSUE TITLE
audio crash

### ISSUE THREAD

**Issue by mauiaaron** [mauiaaron/apple2#9]
```
*** Error in `/home/asc/Documents/00web/apple2/apple2ix': free(): corrupted unsorted chunks: 0x00007fffe0000940 ***

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe8e8d700 (LWP 30881)]
0x00007ffff6569107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6569107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff656a4e8 in __GI_abort () at abort.c:89
#2  0x00007ffff65a7044 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff6699c60 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff65ac81e in malloc_printerr (action=1, str=0x7ffff6699dd0 "free(): corrupted unsorted chunks", ptr=<optimized out>) at malloc.c:4996
#4  0x00007ffff65ad526 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x000000000042b9bb in PlaylistDequeue (voice=0xcbcba0, node=0xcf6af0) at src/audio/soundcore-openal.c:89
#6  0x00000000004310eb in _ALProcessPlayBuffers (voice=0xcbcba0, bytes_queued=0x7fffe8e8cb74) at src/audio/soundcore-openal.c:448
#7  0x000000000042d6c9 in ALGetPosition (_this=0xcbcba0, bytes_queued=0x7fffe8e8cbf8, unused_write_cursor=0x7fffe8e8cbf0) at src/audio/soundcore-openal.c:475
#8  0x0000000000431c3c in Spkr_SubmitWaveBuffer (pSpeakerBuffer=0x108fe70, nNumSamples=22) at src/audio/speaker.c:1030
#9  0x00000000004323dd in SpkrUpdate (totalcycles=1020) at src/audio/speaker.c:701
#10 0x000000000040f150 in cpu_thread (dummyptr=0x0) at src/timing.c:266
#11 0x00007ffff6b000a4 in start_thread (arg=0x7fffe8e8d700) at pthread_create.c:309
#12 0x00007ffff6619ccd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) frame 5
#5  0x000000000042b9bb in PlaylistDequeue (voice=0xcbcba0, node=0xcf6af0) at src/audio/soundcore-openal.c:89
89	    HASH_DEL(voice->queued_buffers, node);              // remove from hash
```

**Comment by mauiaaron** [comment]
Believe fixes or no longer relevant
